services:
  - type: web
    name: versefilter
    runtime: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/versefilter-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17