# Connection string
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/versefilter}
spring.datasource.username=postgres
spring.datasource.password=e4magrify

# Driver and Dialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG